### ISSUE TITLE
TODO: overhaul and update the section for CAN/DBC resources

### ISSUE THREAD

**Issue by nberlette** [nberlette/canbus#4]
wda                                                                                               
                                                                                                  
                                                                                                  
                                                                                                  
                                                ### Add new resources to the list:

- [x] [**DBC Language Syntax**][1] ([VSCode Extension][2])
- [x] [**pydbc Python Library**][3] (parse/interpret `.dbc`)
- [ ] `... to be continued`

[1]: https://github.com/bmwcd/DBC-Language-Syntax
[2]: https://marketplace.visualstudio.com/items?itemName=lharri73.dbc
[3]: https://github.com/nberlette/pyDBC
