### ISSUE TITLE
TODO: complete the missing sections of the wiki's `.dbc` spec.

### ISSUE THREAD

**Issue by nberlette** [nberlette/canbus#5]
### Sections: Completed and Incomplete 

- [x] **Network**
  - [x] Version
  - [x] BitSpeed (`BS_`)
  - [x] Node List (Board Units)
  - [x] New Symbols (`NS_`)

- [x] **Messages (`BO_`)**
  - [ ] Transmitters (`BO_TX_BU_`)
  - [ ] Attributes (`BA_ BO_`)
  - [ ] Comments (`CM_ BO_`)

- [x] **Signals (`SG_`)**
  - [ ] Multiplexers (`SG_ M`)
  - [ ] Multiplexed Signal Values (`SG_MUL_VAL_`)
  - [ ] Attributes (`BA_ SG_`)
  - [ ] Comments (`CM_ SG_`)
  - [ ] Examples

- [x] **Attributes (`BA_`)**
  - [ ] Definitions (`BA_DEF_`)
  - [ ] Default Values (`BA_DEF_DEF_`)
  - [ ] Relation Definitions (`BA_DEF_REL_`)
  - [ ] Relation Default Values (`BA_DEF_DEF_REL_`) 

- [x] **Comments (`CM_`)**
  - [x] Globals/Doc. Comments (`CM_`)
  - [ ] Children of `BU_`, `BO_`, `SG_`

- [x] **Values (`VAL_`)**
  - [ ] Value Tables (`VAL_TABLE_`)

###
